// Example NASA bioscience publications data
export const publications = [
  {
    id: 1,
    title: "Gene Expression in Space-Grown Arabidopsis",
    year: 2022,
    authors: ["Dr. Jane Smith", "Dr. Alan Brown"],
    abstract: "This study investigates gene expression changes in Arabidopsis thaliana grown aboard the ISS, revealing key adaptations to microgravity.",
    keywords: ["Arabidopsis", "Gene Expression", "Microgravity", "ISS"],
    experiment: "Plants grown in microgravity aboard the ISS for 30 days.",
    results: "Significant upregulation of stress response genes and altered root morphology observed.",
  },
  {
    id: 2,
    title: "Human Immune System Response to Spaceflight",
    year: 2019,
    authors: ["Dr. Emily White", "Dr. John Lee"],
    abstract: "Analysis of astronaut blood samples pre- and post-flight shows immune dysregulation during long-duration missions.",
    keywords: ["Immune System", "Astronauts", "Spaceflight", "Blood Analysis"],
    experiment: "Blood samples collected from astronauts before and after 6-month ISS missions.",
    results: "Decreased T-cell activity and increased inflammation markers detected post-flight.",
  },
  {
    id: 3,
    title: "Bacterial Growth Patterns in Microgravity",
    year: 2015,
    authors: ["Dr. Maria Garcia"],
    abstract: "Microgravity alters the growth rate and biofilm formation of E. coli, with implications for astronaut health.",
    keywords: ["Bacteria", "E. coli", "Biofilm", "Microgravity"],
    experiment: "E. coli cultures grown on the ISS and compared to ground controls.",
    results: "Enhanced biofilm formation and antibiotic resistance observed in space-grown samples.",
  },
  {
    id: 4,
    title: "Muscle Atrophy in Long-Duration Spaceflight",
    year: 2021,
    authors: ["Dr. Robert Chen", "Dr. Sarah Johnson"],
    abstract: "Comprehensive analysis of skeletal muscle changes in astronauts during extended ISS missions.",
    keywords: ["Muscle Atrophy", "Astronauts", "Exercise", "Protein Synthesis"],
    experiment: "Muscle biopsies and MRI scans of astronauts before, during, and after 6-12 month missions.",
    results: "20-30% muscle mass loss despite exercise countermeasures, with recovery taking 6+ months.",
  },
  {
    id: 5,
    title: "Radiation Effects on DNA Repair Mechanisms",
    year: 2020,
    authors: ["Dr. Lisa Park", "Dr. Michael Torres"],
    abstract: "Investigation of how space radiation affects cellular DNA repair processes in mammalian cells.",
    keywords: ["Radiation", "DNA Repair", "Space Environment", "Cellular Biology"],
    experiment: "Cell cultures exposed to simulated space radiation and analyzed for DNA damage responses.",
    results: "Impaired DNA repair efficiency and increased mutation rates observed under radiation exposure.",
  },
  {
    id: 6,
    title: "Bone Density Loss in Microgravity",
    year: 2018,
    authors: ["Dr. Amanda Wilson", "Dr. David Kim"],
    abstract: "Longitudinal study of bone mineral density changes in astronauts during ISS missions.",
    keywords: ["Bone Density", "Osteoporosis", "Calcium", "Exercise Countermeasures"],
    experiment: "DEXA scans and blood markers tracked in 50 astronauts over 2-year period.",
    results: "1-2% bone loss per month in weight-bearing bones, with partial recovery post-flight.",
  },
  {
    id: 7,
    title: "Plant Root Development in Reduced Gravity",
    year: 2023,
    authors: ["Dr. Jennifer Martinez", "Dr. Thomas Anderson"],
    abstract: "Study of gravitropic responses and root architecture in various plant species under microgravity conditions.",
    keywords: ["Plant Biology", "Root Development", "Gravitropism", "Agriculture"],
    experiment: "Multiple plant species grown in rotating bioreactor to simulate microgravity effects.",
    results: "Altered root branching patterns and reduced gravitropic sensitivity in space-grown plants.",
  },
  {
    id: 8,
    title: "Cardiovascular Deconditioning During Spaceflight",
    year: 2017,
    authors: ["Dr. Mark Thompson", "Dr. Rachel Davis"],
    abstract: "Comprehensive cardiovascular assessment of astronauts before, during, and after long-duration missions.",
    keywords: ["Cardiovascular", "Heart Function", "Blood Pressure", "Orthostatic Intolerance"],
    experiment: "Echocardiography, blood pressure monitoring, and exercise tests conducted on 30 astronauts.",
    results: "Significant cardiac muscle atrophy and orthostatic intolerance requiring months of rehabilitation.",
  }
];
